/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.awt.datatransfer.StringSelection;
/**
 *
 * @author rudsr
 */
public class appointmentManager extends javax.swing.JFrame
{
    
    private dbConnection db;
    
    
    /**
     * Creates new form appointmentManager
     */
    public appointmentManager(dbConnection db) 
    {
        this.db = db;
        initComponents();
        loadAppointmentsIntoTable();
        setupTableCopy();
    }
  
    private void loadAppointmentsIntoTable() 
    {
        DefaultTableModel model = (DefaultTableModel) ApointmentMtable.getModel();
        model.setRowCount(0);

        try (Connection conn = db.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM Appointments")) {

            while (rs.next()) 
            {
                model.addRow(new Object[]{
                    rs.getInt("AppointmentID"),
                    rs.getString("StudentName"),
                    rs.getString("CounselorID"),
                    rs.getString("Date"),
                    rs.getString("Time"),
                    rs.getString("Status")
                });
            }
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Error loading appointments: " + ex.getMessage());
        }
    }
    private void clearFields() 
    {
        txtFieldAMStudentName.setText("");
        txtFieldAMCounselorID.setText("");
        txtFieldAMDate.setText("");
        txtFieldAMTime.setText("");
        txtFieldAMStatus.setText("");
    }
     
    private void setupTableCopy() {
        ApointmentMtable.setCellSelectionEnabled(true);
        ApointmentMtable.getInputMap().put(KeyStroke.getKeyStroke("ctrl C"), "copy");
        ApointmentMtable.getActionMap().put("copy", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                StringSelection selection = new StringSelection(getSelectedTableCells());
                Toolkit.getDefaultToolkit().getSystemClipboard().setContents(selection, selection);
            }
        });
    }
    
    private String getSelectedTableCells() {
        int[] rows = ApointmentMtable.getSelectedRows();
        int[] cols = ApointmentMtable.getSelectedColumns();
        StringBuilder sb = new StringBuilder();

        for (int row : rows) {
            for (int i = 0; i < cols.length; i++) {
                Object value = ApointmentMtable.getValueAt(row, cols[i]);
                sb.append(value == null ? "" : value.toString());
                if (i < cols.length - 1) sb.append("\t");
            }
            sb.append("\n");
        }
        return sb.toString();
    }
    
        private void btnAMaddActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String studentName = txtFieldAMStudentName.getText().trim();
        String counselorID = txtFieldAMCounselorID.getText().trim();
        String date = txtFieldAMDate.getText().trim();
        String time = txtFieldAMTime.getText().trim();
        String status = txtFieldAMStatus.getText().trim();

        if (studentName.isEmpty() || counselorID.isEmpty() || date.isEmpty() || time.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        try (Connection conn = db.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO Appointments (StudentName, CounselorID, Date, Time, Status) VALUES (?, ?, ?, ?, ?)")) {

            ps.setString(1, studentName);
            ps.setString(2, counselorID);
            ps.setString(3, date);
            ps.setString(4, time);
            ps.setString(5, status);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Appointment added successfully.");
            loadAppointmentsIntoTable();
            clearFields();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error adding appointment: " + ex.getMessage());
        }
    }
    // Event handler for Main Menu button


    // Event handler for Exit button
    private void btnAMexitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ApointmentMtable = new javax.swing.JTable();
        btnAMadd = new javax.swing.JButton();
        btnAMmainmenu = new javax.swing.JButton();
        btnAMexit = new javax.swing.JButton();
        lableStudentname = new javax.swing.JLabel();
        lableCounselorId = new javax.swing.JLabel();
        lableDate = new javax.swing.JLabel();
        lableTime = new javax.swing.JLabel();
        lableStatus = new javax.swing.JLabel();
        txtFieldAMStudentName = new javax.swing.JTextField();
        txtFieldAMCounselorID = new javax.swing.JTextField();
        txtFieldAMDate = new javax.swing.JTextField();
        txtFieldAMTime = new javax.swing.JTextField();
        txtFieldAMStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ApointmentMtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ApointmentMtable);

        btnAMadd.setText("Add New");

        btnAMmainmenu.setText("Main Menu");
        btnAMmainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMmainmenuActionPerformed(evt);
            }
        });

        btnAMexit.setText("Exit");

        lableStudentname.setText("Student Name:");

        lableCounselorId.setText("Counselor ID:");

        lableDate.setText("Date:");

        lableTime.setText("Time:");

        lableStatus.setText("Status");

        txtFieldAMStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAMStudentNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAMadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lableStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldAMStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAMexit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAMmainmenu))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lableStudentname)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lableCounselorId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFieldAMCounselorID, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtFieldAMStudentName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableDate)
                            .addComponent(lableTime))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldAMTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtFieldAMDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableStudentname)
                    .addComponent(lableDate)
                    .addComponent(lableStatus)
                    .addComponent(txtFieldAMStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAMDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAMStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableCounselorId)
                    .addComponent(lableTime)
                    .addComponent(txtFieldAMCounselorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAMTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAMmainmenu)
                    .addComponent(btnAMexit)
                    .addComponent(btnAMadd))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAMmainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMmainmenuActionPerformed

    }//GEN-LAST:event_btnAMmainmenuActionPerformed

    private void txtFieldAMStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAMStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAMStudentNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appointmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appointmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appointmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appointmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        dbConnection db = new dbConnection();
        java.awt.EventQueue.invokeLater(() -> {
            new appointmentManager(db).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ApointmentMtable;
    private javax.swing.JButton btnAMadd;
    private javax.swing.JButton btnAMexit;
    private javax.swing.JButton btnAMmainmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableCounselorId;
    private javax.swing.JLabel lableDate;
    private javax.swing.JLabel lableStatus;
    private javax.swing.JLabel lableStudentname;
    private javax.swing.JLabel lableTime;
    private javax.swing.JTextField txtFieldAMCounselorID;
    private javax.swing.JTextField txtFieldAMDate;
    private javax.swing.JTextField txtFieldAMStatus;
    private javax.swing.JTextField txtFieldAMStudentName;
    private javax.swing.JTextField txtFieldAMTime;
    // End of variables declaration//GEN-END:variables
