/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 * MainMenu.java
 * 
 * This class represents the main menu of the application.
 * It provides buttons for users to navigate to various modules:
 * - Student Management
 * - Counselor Management
 * - Booking Management
 * - Feedback Management
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Constructor - Initializes components and sets up the main menu UI
     */
    public MainMenu() {
        initComponents(); // Builds the GUI components (auto-generated by NetBeans)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Auto-generated method to initialize UI components (buttons, labels, layout, etc.)
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMMtmember = new javax.swing.JButton();
        btnMMcmanager = new javax.swing.JButton();
        btnMMfmanger = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnMMamanager1 = new javax.swing.JButton();
        btnMMexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(169, 210, 243));
        jPanel1.setMaximumSize(new java.awt.Dimension(1069, 693));

        btnMMtmember.setBackground(new java.awt.Color(237, 241, 245));
        btnMMtmember.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnMMtmember.setText("Team Members");
        btnMMtmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMtmemberActionPerformed(evt);
            }
        });

        btnMMcmanager.setBackground(new java.awt.Color(237, 241, 245));
        btnMMcmanager.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnMMcmanager.setText("Counselor Manager");
        btnMMcmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMcmanagerActionPerformed(evt);
            }
        });

        btnMMfmanger.setBackground(new java.awt.Color(237, 241, 245));
        btnMMfmanger.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnMMfmanger.setText("Feedback Manager");
        btnMMfmanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMfmangerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(22, 91, 139));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wellness Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnMMamanager1.setBackground(new java.awt.Color(237, 241, 245));
        btnMMamanager1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnMMamanager1.setText("Appointment Manager");
        btnMMamanager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMamanager1ActionPerformed(evt);
            }
        });

        btnMMexit.setBackground(new java.awt.Color(227, 153, 172));
        btnMMexit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMMexit.setForeground(new java.awt.Color(255, 255, 255));
        btnMMexit.setText("Exit");
        btnMMexit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnMMexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMMcmanager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMMamanager1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMMfmanger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMMtmember, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(253, 253, 253))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMMexit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMMfmanger, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMMamanager1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMMcmanager, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMMtmember, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnMMexit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Exit button action – closes the application
    private void btnMMexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMexitActionPerformed
        System.exit(0);// Terminates the program
    }//GEN-LAST:event_btnMMexitActionPerformed

    private void btnMMfmangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMfmangerActionPerformed
        feedbackManagement fm = new feedbackManagement();// Create Feedback Manager form
        fm.setVisible(true);// Show it
        this.dispose(); // Close current MainMenu
    }//GEN-LAST:event_btnMMfmangerActionPerformed
// Opens the Counselor Management interface
    private void btnMMcmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMcmanagerActionPerformed
        counselorManagement cm = new counselorManagement();// Create Counselor Manager form
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMMcmanagerActionPerformed
// Opens the Team Members screen
    private void btnMMtmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMtmemberActionPerformed
        TeamMembers tm = new TeamMembers();// Create TeamMembers window
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMMtmemberActionPerformed
// Opens Appointment Manager, checks DB connection first
    private void btnMMamanager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMamanager1ActionPerformed
            // Ensure database connection is initialized
        if (AppSession.db == null) {
            JOptionPane.showMessageDialog(this, "Database not connected!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            new appointmentManager(AppSession.db).setVisible(true);// Open appointments screen
            this.dispose();// Close main menu
        }
    }//GEN-LAST:event_btnMMamanager1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Initialize a global database connection for the session
    AppSession.db = new dbConnection();
    try {
        // Attempt to connect to the DB and create required tables
        AppSession.db.connect();
        AppSession.db.createTables();
        
        // Ensure DB is closed safely when the application exits
        Runtime.getRuntime().addShutdownHook(new Thread(() -> AppSession.db.close()));

        // Launch the Main Menu UI on the Event Dispatch Thread
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true); // Start at MainMenu
        });
    } catch (ClassNotFoundException e) {
        // Display error if the JDBC driver is not found
        JOptionPane.showMessageDialog(null, "Database driver not found: " + e.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMMamanager1;
    private javax.swing.JButton btnMMcmanager;
    private javax.swing.JButton btnMMexit;
    private javax.swing.JButton btnMMfmanger;
    private javax.swing.JButton btnMMtmember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
